#!/usr/bin/env python


print ("hello world")
a = 4
print a
print id(a)
a = 5
print a
print id(a)

b = []
print id(b)
b.append(3)
print b
print id(b)

c = 3/4
d = 3/4.

print c, d
print('He said, "I\'m sorry"')
print '''He said, "I'm sorry"'''
print """He said, "I'm sorry\""""
print """He said, "I'm" sorry"""